config/routes.rb
Rails.application.routes.draw do
  root "store#index", as: 'root'
  get '/home', to: "store#index", as: "home"
  get '/api/products.json', to: "store#api_index", as: "api_products"

  get "/auth/signup", to: "auth#get_signup", as: "signup"
  post "/auth/signup", to: "auth#post_signup"
  get "/auth/login", to: "auth#get_login", as: "login"
  post "/auth/login", to: "auth#post_login"
  post "/auth/logout", to: "auth#post_logout", as: "logout"
  post "/api/auth/login", to: "auth#api_login", as: "api_login"

  get "/api/user", to: "user#api_profile", as: "api_profile"

  get '/admin/create', to: "admin#create", as: "create"
  post '/admin/create', to: "admin#post_create"
  get '/admin/edit/:id', to: "admin#edit", as: "edit"
  post '/admin/edit/:id', to: "admin#post_edit"
  get '/admin/delete/:id', to: "admin#delete", as: "delete"
  post '/admin/delete/:id', to: "admin#delete_delete", as: "delete_confirm"
  post '/api/products.json', to: "admin#api_create"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/admin/_form.html.erb
  <div class="mb-3">
    <label for="rocket_Name" class="form-label">Name</label>
    <%= form.text_field :Name, class: "form-control #{'is-invalid' if @rocket.errors[:Name].present?}", id: "rocket_Name" %>
    <% if @rocket.errors[:Name].present? %>
      <div class="invalid-feedback d-block">
        <%= @rocket.errors[:Name].first %>
      </div>
    <% end %>
  </div>
  <div class="mb-3">
    <label for="rocket_Price" class="form-label">Price</label>
    <%= form.number_field :Price, class: "form-control #{'is-invalid' if @rocket.errors[:Price].present?}", id: "rocket_Price" %>
    <% if @rocket.errors[:Price].present? %>
      <div class="invalid-feedback d-block">
        <%= @rocket.errors[:Price].first %>
      </div>
    <% end %>
  </div>
  <div class="mb-3">
    <label for="rocket_description" class="form-label">Description</label>
    <%= form.rich_text_area :description, class: "form-control #{'is-invalid' if @rocket.errors[:description].present?}", id: "rocket_description", rows: 3 %>
    <% if @rocket.errors[:description].present? %>
      <div class="invalid-feedback d-block">
        <%= @rocket.errors[:description].first %>
      </div>
    <% end %>
  </div>
  <div class="mb-3">
    <label for="rocket_Image" class="form-label">Thumbnail</label>
    <%= form.file_field :image, class: "form-control #{'is-invalid' if @rocket.errors[:image].present?}", id: "rocket_Image" %>
    <% if @rocket.errors[:image].present? %>
      <div class="invalid-feedback d-block">
        <%= @rocket.errors[:image].first %>
      </div>
    <% end %>
  </div>
  <div class="mb-3">
    <label for="rocket_Image" class="form-label">Launch At</label>
    <%= form.datetime_local_field :launch_at, class: "form-control #{'is-invalid' if @rocket.errors[:image].present?}", id: "rocket_LaunchAt" %>
    <% if @rocket.errors[:launch_at].present? %>
      <div class="invalid-feedback d-block">
        <%= @rocket.errors[:launch_at].first %>
      </div>
    <% end %>
  </div>

app/views/admin/create.html.erb
<div class="container_admin container-fluid" data-turbo="false">
  <h4 class="mb-3">Create Product</h4>
  <%= form_with(model: @rocket, url: create_path, method: :post ,class: 'needs-validation', novalidate: true) do |form| %>
    <%= render partial: 'admin/form' , locals: { form: form } %>
    <%= form.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/delete.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal fade" id="bsModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= form_with(url: delete_confirm_path, method: :post) do |form| %>
          <div class="modal-header">
            <h5 class="modal-title">Edit Product</h5>
          </div>
          <div class="modal-body">
            Are you sure you want to delete this product?
          </div>
          <div class="modal-footer">
            <%= form.submit "Yes, Delete", onclick: 'BS_MODAL.hide()', class: "btn btn-danger" %>
            <%= link_to "Cancel", nil, onclick: 'BS_MODAL.hide()', class: "btn", data: {
              controller: "modals",
              action: "modals#close"
            } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <script>
      window.BS_MODAL = new bootstrap.Modal("#bsModal");
      BS_MODAL.show();
  </script>
<% end %>

app/views/admin/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal fade" id="bsModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= form_with(model: @rocket, url: edit_path, method: :post, class: 'needs-validation', novalidate: true) do |form| %>
          <div class="modal-header">
            <h5 class="modal-title">Edit Product</h5>
          </div>
          <div class="modal-body">
            <%= render partial: 'admin/form', locals: { form: form } %>
          </div>
          <div class="modal-footer">
            <%= form.submit "Save", onclick: 'BS_MODAL.hide()', class: "btn btn-primary" %>
            <%= link_to "Cancel", nil, onclick: 'BS_MODAL.hide()', class: "btn", data: {
              controller: "modals",
              action: "modals#close"
            } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <script>
      window.BS_MODAL = new bootstrap.Modal("#bsModal");
      BS_MODAL.show();
  </script>
<% end %>

app/views/admin/index.html.erb
<div class="container_admin" data-turbo="false">
  <br><br>
  <h4 class="mb-3">Create Product</h4>
  <%= form_with(model: @rocket, url: admin_create_path, method: :post ,class: 'needs-validation', novalidate: true) do |form| %>
    <div class="mb-3">
      <label for="rocket_Name" class="form-label">Name</label>
      <%= form.text_field :Name, class: "form-control #{'is-invalid' if @rocket.errors[:Name].present?}", id: "rocket_Name" %>
      <% if @rocket.errors[:Name].present? %>
        <div class="invalid-feedback d-block">
          <%= @rocket.errors[:Name].first %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <label for="rocket_Price" class="form-label">Price</label>
      <%= form.number_field :Price, class: "form-control #{'is-invalid' if @rocket.errors[:Price].present?}", id: "rocket_Price" %>
      <% if @rocket.errors[:Price].present? %>
        <div class="invalid-feedback d-block">
          <%= @rocket.errors[:Price].first %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <label for="rocket_description" class="form-label">Description</label>
      <%= form.text_area :description, class: "form-control #{'is-invalid' if @rocket.errors[:description].present?}", id: "rocket_description", rows: 3 %>
      <% if @rocket.errors[:description].present? %>
        <div class="invalid-feedback d-block">
          <%= @rocket.errors[:description].first %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <label for="rocket_Image" class="form-label">Image</label>
      <%= form.text_field :Image, class: "form-control #{'is-invalid' if @rocket.errors[:Image].present?}", id: "rocket_Image" %>
      <% if @rocket.errors[:Image].present? %>
        <div class="invalid-feedback d-block">
          <%= @rocket.errors[:Image].first %>
        </div>
      <% end %>
    </div>
    <%= form.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>