config/routes.rb
Rails.application.routes.draw do
  root "store#index", as: 'root'
  get '/home', to: "store#index", as: "home"
  get '/api/products.json', to: "store#api_index", as: "api_products"

  get "/auth/signup", to: "auth#get_signup", as: "signup"
  post "/auth/signup", to: "auth#post_signup"
  get "/auth/login", to: "auth#get_login", as: "login"
  post "/auth/login", to: "auth#post_login"
  post "/auth/logout", to: "auth#post_logout", as: "logout"
  post "/api/auth/login", to: "auth#api_login", as: "api_login"

  get "/api/user", to: "user#api_profile", as: "api_profile"

  get '/admin/create', to: "admin#create", as: "create"
  post '/admin/create', to: "admin#post_create"
  get '/admin/edit/:id', to: "admin#edit", as: "edit"
  post '/admin/edit/:id', to: "admin#post_edit"
  get '/admin/delete/:id', to: "admin#delete", as: "delete"
  post '/admin/delete/:id', to: "admin#delete_delete", as: "delete_confirm"
  post '/api/products.json', to: "admin#api_create"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @rockets = Rocket.all
  end

  def api_index
    @rockets = Rocket.all
    render json: @rockets.map { |rocket| rocket.api_mapping }
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/index.html.erb
<div class="container">
  <h3 class="my-4">Rockets</h3>

  <% flash.each do |type, msg| %>
    <div class="alert alert-success mb-3">
      <i class="bi bi-check-circle text-success mr-2"></i>
      <%= msg %>
    </div>
  <% end %>

  <div class="row">
    <% @rockets.each do |rocket| %>
      <div class="col-sm-3 mb-3 mb-sm-0">
        <div class="card mb-3">
          <%= image_tag(rocket.image_as_thumbnail, class: "card-img-top") if rocket.image.attached? %>
          <div class="card-body">
            <h5 class="card-title"><%= rocket.Name %></h5>
            <p class="card-text"><%= rocket.description %></p>
            <small class="text-muted">Launch at <%= rocket.launch_at.strftime("%e %b %y, %I:%M %p") %></small>
            <div class="d-flex align-items-center justify-content-between mt-2">
              <div class="d-flex">
                <% if session[:current_user_id].present? %>
                  <%= link_to edit_path(rocket.id), class: "btn", data: {
                    turbo_frame: "modal",
                  } do %>
                    <i class="bi bi-pencil"></i>
                  <% end %>
                  <%= link_to delete_path(rocket.id), class: "btn", data: {
                    turbo_frame: "modal",
                  } do %>
                    <i class="bi bi-trash text-danger"></i>
                  <% end %>
                <% end %>
              </div>
              <b class="d-block text-success"><%= rocket.Price %> BTC</b>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>