config/routes.rb
Rails.application.routes.draw do
  root "store#index", as: 'root'
  get '/home', to: "store#index", as: "home"
  get '/api/products.json', to: "store#api_index", as: "api_products"

  get "/auth/signup", to: "auth#get_signup", as: "signup"
  post "/auth/signup", to: "auth#post_signup"
  get "/auth/login", to: "auth#get_login", as: "login"
  post "/auth/login", to: "auth#post_login"
  post "/auth/logout", to: "auth#post_logout", as: "logout"
  post "/api/auth/login", to: "auth#api_login", as: "api_login"

  get "/api/user", to: "user#api_profile", as: "api_profile"

  get '/admin/create', to: "admin#create", as: "create"
  post '/admin/create', to: "admin#post_create"
  get '/admin/edit/:id', to: "admin#edit", as: "edit"
  post '/admin/edit/:id', to: "admin#post_edit"
  get '/admin/delete/:id', to: "admin#delete", as: "delete"
  post '/admin/delete/:id', to: "admin#delete_delete", as: "delete_confirm"
  post '/api/products.json', to: "admin#api_create"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rocket Plaza</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<nav class="navbar bg-dark border-bottom border-body navbar-expand-lg" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= home_path %>">Rocket Plaza</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= home_path %>">Home</a>
        </li>
        <% if session[:current_user_id].present? %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= create_path %>">Create Product</a>
          </li>
        <% end %>
      </ul>
      <% if session[:current_user_id].present? %>
        <form class="d-flex" action="/auth/logout" method="post">
          <button class="btn" type="submit">Logout</button>
        </form>
      <% else %>
        <a href="<%= login_path %>" class="d-flex btn me-2" type="submit">Login</a>
        <a href="<%= signup_path %>" class="d-flex btn btn-primary" type="submit">Sign up</a>
      <% end %>
    </div>
  </div>
</nav>
<%= turbo_frame_tag "modal" %>
<turbo-frame id="page">
  <%= yield %>
</turbo-frame>
<script type="module">
    import * as bootstrap from "bootstrap";
</script>
</body>
</html>